/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Paciente } from "./Paciente";
import { PacienteCountArgs } from "./PacienteCountArgs";
import { PacienteFindManyArgs } from "./PacienteFindManyArgs";
import { PacienteFindUniqueArgs } from "./PacienteFindUniqueArgs";
import { CreatePacienteArgs } from "./CreatePacienteArgs";
import { UpdatePacienteArgs } from "./UpdatePacienteArgs";
import { DeletePacienteArgs } from "./DeletePacienteArgs";
import { PacienteService } from "../paciente.service";
@graphql.Resolver(() => Paciente)
export class PacienteResolverBase {
  constructor(protected readonly service: PacienteService) {}

  async _pacientesMeta(
    @graphql.Args() args: PacienteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Paciente])
  async pacientes(
    @graphql.Args() args: PacienteFindManyArgs
  ): Promise<Paciente[]> {
    return this.service.pacientes(args);
  }

  @graphql.Query(() => Paciente, { nullable: true })
  async paciente(
    @graphql.Args() args: PacienteFindUniqueArgs
  ): Promise<Paciente | null> {
    const result = await this.service.paciente(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Paciente)
  async createPaciente(
    @graphql.Args() args: CreatePacienteArgs
  ): Promise<Paciente> {
    return await this.service.createPaciente({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Paciente)
  async updatePaciente(
    @graphql.Args() args: UpdatePacienteArgs
  ): Promise<Paciente | null> {
    try {
      return await this.service.updatePaciente({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Paciente)
  async deletePaciente(
    @graphql.Args() args: DeletePacienteArgs
  ): Promise<Paciente | null> {
    try {
      return await this.service.deletePaciente(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
