/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Receitas } from "./Receitas";
import { ReceitasCountArgs } from "./ReceitasCountArgs";
import { ReceitasFindManyArgs } from "./ReceitasFindManyArgs";
import { ReceitasFindUniqueArgs } from "./ReceitasFindUniqueArgs";
import { DeleteReceitasArgs } from "./DeleteReceitasArgs";
import { ReceitasService } from "../receitas.service";
@graphql.Resolver(() => Receitas)
export class ReceitasResolverBase {
  constructor(protected readonly service: ReceitasService) {}

  async _receitasItemsMeta(
    @graphql.Args() args: ReceitasCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Receitas])
  async receitasItems(
    @graphql.Args() args: ReceitasFindManyArgs
  ): Promise<Receitas[]> {
    return this.service.receitasItems(args);
  }

  @graphql.Query(() => Receitas, { nullable: true })
  async receitas(
    @graphql.Args() args: ReceitasFindUniqueArgs
  ): Promise<Receitas | null> {
    const result = await this.service.receitas(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Receitas)
  async deleteReceitas(
    @graphql.Args() args: DeleteReceitasArgs
  ): Promise<Receitas | null> {
    try {
      return await this.service.deleteReceitas(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
