/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CampanhasDeMarketing as PrismaCampanhasDeMarketing,
} from "@prisma/client";

export class CampanhasDeMarketingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CampanhasDeMarketingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.campanhasDeMarketing.count(args);
  }

  async campanhasDeMarketings<
    T extends Prisma.CampanhasDeMarketingFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CampanhasDeMarketingFindManyArgs>
  ): Promise<PrismaCampanhasDeMarketing[]> {
    return this.prisma.campanhasDeMarketing.findMany<Prisma.CampanhasDeMarketingFindManyArgs>(
      args
    );
  }
  async campanhasDeMarketing<
    T extends Prisma.CampanhasDeMarketingFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CampanhasDeMarketingFindUniqueArgs>
  ): Promise<PrismaCampanhasDeMarketing | null> {
    return this.prisma.campanhasDeMarketing.findUnique(args);
  }
  async createCampanhasDeMarketing<
    T extends Prisma.CampanhasDeMarketingCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CampanhasDeMarketingCreateArgs>
  ): Promise<PrismaCampanhasDeMarketing> {
    return this.prisma.campanhasDeMarketing.create<T>(args);
  }
  async updateCampanhasDeMarketing<
    T extends Prisma.CampanhasDeMarketingUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CampanhasDeMarketingUpdateArgs>
  ): Promise<PrismaCampanhasDeMarketing> {
    return this.prisma.campanhasDeMarketing.update<T>(args);
  }
  async deleteCampanhasDeMarketing<
    T extends Prisma.CampanhasDeMarketingDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CampanhasDeMarketingDeleteArgs>
  ): Promise<PrismaCampanhasDeMarketing> {
    return this.prisma.campanhasDeMarketing.delete(args);
  }
}
