/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgendamentoCreateNestedManyWithoutPacientesItemsInput } from "./AgendamentoCreateNestedManyWithoutPacientesItemsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ConsultaCreateNestedManyWithoutPacientesItemsInput } from "./ConsultaCreateNestedManyWithoutPacientesItemsInput";
import { ConsultasCreateNestedManyWithoutPacientesItemsInput } from "./ConsultasCreateNestedManyWithoutPacientesItemsInput";
import { ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput } from "./ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput";

@InputType()
class PacientesCreateInput {
  @ApiProperty({
    required: false,
    type: () => AgendamentoCreateNestedManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => AgendamentoCreateNestedManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => AgendamentoCreateNestedManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  agendamentos?: AgendamentoCreateNestedManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: () => ConsultaCreateNestedManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ConsultaCreateNestedManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ConsultaCreateNestedManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  consultas?: ConsultaCreateNestedManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: () => ConsultasCreateNestedManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ConsultasCreateNestedManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ConsultasCreateNestedManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  consultasItems?: ConsultasCreateNestedManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endereO?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  histRicoMDico?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  prontuRiosEletrNicosItems?: ProntuRiosEletrNicosCreateNestedManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefone?: string | null;
}

export { PacientesCreateInput as PacientesCreateInput };
