/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgendamentoListRelationFilter } from "../../agendamento/base/AgendamentoListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { ConsultaListRelationFilter } from "../../consulta/base/ConsultaListRelationFilter";
import { ConsultasListRelationFilter } from "../../consultas/base/ConsultasListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { ProntuRiosEletrNicosListRelationFilter } from "../../prontuRiosEletrNicos/base/ProntuRiosEletrNicosListRelationFilter";

@InputType()
class PacientesWhereInput {
  @ApiProperty({
    required: false,
    type: () => AgendamentoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AgendamentoListRelationFilter)
  @IsOptional()
  @Field(() => AgendamentoListRelationFilter, {
    nullable: true,
  })
  agendamentos?: AgendamentoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ConsultaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ConsultaListRelationFilter)
  @IsOptional()
  @Field(() => ConsultaListRelationFilter, {
    nullable: true,
  })
  consultas?: ConsultaListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ConsultasListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ConsultasListRelationFilter)
  @IsOptional()
  @Field(() => ConsultasListRelationFilter, {
    nullable: true,
  })
  consultasItems?: ConsultasListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  endereO?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  histRicoMDico?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nome?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProntuRiosEletrNicosListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProntuRiosEletrNicosListRelationFilter)
  @IsOptional()
  @Field(() => ProntuRiosEletrNicosListRelationFilter, {
    nullable: true,
  })
  prontuRiosEletrNicosItems?: ProntuRiosEletrNicosListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  telefone?: StringNullableFilter;
}

export { PacientesWhereInput as PacientesWhereInput };
