/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgendamentoUpdateManyWithoutPacientesItemsInput } from "./AgendamentoUpdateManyWithoutPacientesItemsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ConsultaUpdateManyWithoutPacientesItemsInput } from "./ConsultaUpdateManyWithoutPacientesItemsInput";
import { ConsultasUpdateManyWithoutPacientesItemsInput } from "./ConsultasUpdateManyWithoutPacientesItemsInput";
import { ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput } from "./ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput";

@InputType()
class PacientesUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AgendamentoUpdateManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => AgendamentoUpdateManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => AgendamentoUpdateManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  agendamentos?: AgendamentoUpdateManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: () => ConsultaUpdateManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ConsultaUpdateManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ConsultaUpdateManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  consultas?: ConsultaUpdateManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: () => ConsultasUpdateManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ConsultasUpdateManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ConsultasUpdateManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  consultasItems?: ConsultasUpdateManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endereO?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  histRicoMDico?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput,
  })
  @ValidateNested()
  @Type(() => ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput)
  @IsOptional()
  @Field(() => ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput, {
    nullable: true,
  })
  prontuRiosEletrNicosItems?: ProntuRiosEletrNicosUpdateManyWithoutPacientesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefone?: string | null;
}

export { PacientesUpdateInput as PacientesUpdateInput };
