/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Agendamento } from "../../agendamento/base/Agendamento";
import { ValidateNested, IsOptional, IsDate, IsString } from "class-validator";
import { Type } from "class-transformer";
import { Consulta } from "../../consulta/base/Consulta";
import { Consultas } from "../../consultas/base/Consultas";
import { ProntuRiosEletrNicos } from "../../prontuRiosEletrNicos/base/ProntuRiosEletrNicos";

@ObjectType()
class Pacientes {
  @ApiProperty({
    required: false,
    type: () => [Agendamento],
  })
  @ValidateNested()
  @Type(() => Agendamento)
  @IsOptional()
  agendamentos?: Array<Agendamento>;

  @ApiProperty({
    required: false,
    type: () => [Consulta],
  })
  @ValidateNested()
  @Type(() => Consulta)
  @IsOptional()
  consultas?: Array<Consulta>;

  @ApiProperty({
    required: false,
    type: () => [Consultas],
  })
  @ValidateNested()
  @Type(() => Consultas)
  @IsOptional()
  consultasItems?: Array<Consultas>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  endereO!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  histRicoMDico!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome!: string | null;

  @ApiProperty({
    required: false,
    type: () => [ProntuRiosEletrNicos],
  })
  @ValidateNested()
  @Type(() => ProntuRiosEletrNicos)
  @IsOptional()
  prontuRiosEletrNicosItems?: Array<ProntuRiosEletrNicos>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefone!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Pacientes as Pacientes };
